// SPDX-FileCopyrightText: 2024 OGL authors
//
// SPDX-License-Identifier: GPL-3.0-or-later

#include "OGL/lduLduBase.H"

// These variables are autogenerated and compiled
// into the library by the version.cmake script
extern "C" {
extern const char *GIT_TAG;
extern const char *GIT_REV;
extern const char *GINKGO_GIT_REV;
extern const char *GIT_BRANCH;
}

const char *git_version(void) { return GIT_TAG; }

const char *git_revision(void) { return GIT_REV; }

const char *ginkgo_git_revision(void) { return GINKGO_GIT_REV; }

const char *git_branch(void) { return GIT_BRANCH; }
