name: CMake

on: [pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OF: [{repo: "https://github.com/OpenFOAM/OpenFOAM-9.git",
              path: "OpenFOAM-8"},
             {repo: "https://develop.openfoam.com/Development/openfoam.git",
              path: "openfoam"}]
    
    env:
      FOAM_SRC: /home/runner/OpenFOAM/${{ matrix.OF.path }}/src
      FOAM_USER_LIBBIN: /home/go/OpenFOAM/${{ matrix.OF.path }}/platforms
    
    steps:
    - name: Cache OpenFOAM
      uses: actions/cache@v2
      with:
        key: ${{ matrix.OF.path }}
        path: |
          ~/OpenFOAM/${{ matrix.OF.path }}
          
    - name: Cache Ginkgo builds
      uses: actions/cache@v2
      with:
        key: ginkgo-cache
        path: |
          ~/ginkgo
                
    - name: Clone OpenFOAM 
      # Clone OpenFOAM
      run: git clone  --depth 1 ${{ matrix.OF.repo }}  ~/OpenFOAM/${{ matrix.OF.path }}
      
    - name: Show OpenFOAM folder
      # Clone OpenFOAM
      run: ls ~/OpenFOAM/${{ matrix.OF.path }}
      
    - name: Clone Ginkgo 
      # Clone OpenFOAM
      run: git clone  --depth 1 https://github.com/ginkgo-project/ginkgo.git ~/ginkgo
      
    - name: Create Ginkgo Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ~/ginkgo/build
      
    - name: Configure ginkgo CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ~/ginkgo/build/
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGINKGO_BUILD_BENCHMARKS=OFF -DGINKGO_BUILD_EXAMPLES=OFF -DGINKGO_BUILD_CUDA=OFF -DGINKGO_BUILD_HIP=OFF -DGINKGO_BUILD_OMP=ON -DGINKGO_BUILD_TESTS=OFF -DGINKGO_BUILD_REFERENCE=ON -DCMAKE_BUILD_TYPE=Release -DGINKGO_BUILD_HWLOC=OFF -DCMAKE_INSTALL_PREFIX=install

    - name: Build Ginkgo
      working-directory: ~/Ginkgo/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

      
    - uses: actions/checkout@v2

    - name: Create OGL Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
